# Generated by Django 5.2.8 on 2025-11-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmer_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("village", models.CharField(max_length=100)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="core.district",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Herd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("cattle", "Cattle"),
                            ("sheep", "Sheep"),
                            ("goat", "Goat"),
                            ("horse", "Horse"),
                            ("poultry", "Poultry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("headcount", models.IntegerField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="herds",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["animal_type"],
            },
        ),
    ]
