# Generated by Django 5.2.8 on 2025-11-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("disease_outbreak", "Disease Outbreak"),
                            ("vaccination", "Vaccination"),
                            ("inspection", "Inspection"),
                            ("quarantine", "Quarantine"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("resolved", "Resolved"),
                        ],
                        default="reported",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
    ]
